---
sudo: required
language: python
services:
  - docker
addons:
  apt:
    packages:
      - docker-ce
before_install:
  - sudo apt-get -qq update
  # Reconfigure docker to be more efficient
  - |
    echo '{
      "experimental": true,
      "storage-driver": "overlay2",
      "max-concurrent-downloads": 50,
      "max-concurrent-uploads": 50
    }' | sudo tee /etc/docker/daemon.json
  - sudo service docker restart
install:
  # workaround https://github.com/ansible/molecule/issues/2083
  - pip install molecule==2.19 ansible==2.7.11
  # - pip install required driver (e.g. docker, python-vagrant, shade, boto, apache-libcloud)
  - pip install docker
script:
  - molecule lint
  - molecule test
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
